"""Add description to Sound

Revision ID: 2702d5b9dece
Revises: af3150f61c0b
Create Date: 2024-12-20 15:34:08.119287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2702d5b9dece'
down_revision = 'af3150f61c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
