"""added category for beat and sound

Revision ID: 289dcc9d0d52
Revises: 2702d5b9dece
Create Date: 2024-12-20 16:35:22.529904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '289dcc9d0d52'
down_revision = '2702d5b9dece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
