"""added isadmin

Revision ID: 40711b9a2beb
Revises: e8060d0f7906
Create Date: 2024-12-21 10:16:09.764192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40711b9a2beb'
down_revision = 'e8060d0f7906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###
