"""empty message

Revision ID: 975fdea7753d
Revises: 289dcc9d0d52
Create Date: 2024-12-20 16:40:55.659609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '975fdea7753d'
down_revision = '289dcc9d0d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
